name: Development Workflow 3.8

on:
  pull_request:
    branches:
      - 'master'
      -  'main'

jobs:
  build-container:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Build Next.js app
      run: |
        npm install
        npm run build
        npm run export

    - name: Build Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: false
        tags: portfoliodiana:1.1

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: ${{ secrets.HEROKU_USERNAME }}
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Push Docker image to Heroku Container Registry
      env:
        HEROKU_APP_NAME: aaaa-dev
      run: |
        docker tag my-nextjs-app:dev registry.heroku.com/${HEROKU_APP_NAME}/web
        docker push registry.heroku.com/${HEROKU_APP_NAME}/web


  deploy:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: aaaa-dev
          heroku_email: diana.zawislak@icloud.com
          usedocker: true
