name: Production Workflow 1

on:
  push:
    branches:
      - 'main'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: portfoliodiana:1.1

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_USERNAME }}
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Push Docker image to Heroku Container Registry
        run: |
          docker tag portfoliodiana:1.1 registry.heroku.com/diana-portfolio-new/web:latest
          docker push registry.heroku.com/diana-portfolio-new/web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Deploy to Heroku
        uses: actions/checkout@v2
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: diana-portfolio-new
          heroku_email: diana.zawislak@icloud.com
          usedocker: true
